### ISSUE TITLE
Make sure cached list can be deserialized in mod_articles_categories

### ISSUE THREAD

**Issue by stevenrombauts** [joomlatools/joomlatools-platform-categories#21]
mod_articles_categories will throw an exception if it tries to deserialize the cached category list. This happens because `JCategoryNode` is required, but the class is not registered when loading it from cache. 

See:
* [issue #3907](https://issues.joomla.org/tracker/joomla-cms/3907) on Joomla Issue Tracker
*timble/www.scicasts.com#332

**Comment by allanpilarca** [comment]
@stevenrombauts is this ready for PR?

**Comment by johanjanssens** [comment]
@allanpilarca Can you create a PR?
